version: '3'

services:
  reverseproxy:
    image: reverseproxy:latest
    ports:
      - "80"
      - "8080"
    volumes:
      - nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /docker/letsencrypt-docker-nginx/src/production/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/lyricmap.com/fullchain.pem:/etc/letsencrypt/live/lyricmap.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/lyricmap.com/privkey.pem:/etc/letsencrypt/live/lyricmap.com/privkey.pem
    restart: always
    networks:
      - docker-network

  node:
    depends_on:
      - reverseproxy
    image: nodeserver:latest
    restart: always
    env_file:
      - client/env-qa.list
   networks:
      - docker-network

  golang:
    depends_on:
      - reverseproxy
    image: goserver:latest
    restart: always
    env_file:
      - server/env-qa.lis
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
